var responsiveflag=false;var responsiveflag2=false;var isMobile=/Android|webOS|iPhone|iPad|iPod|BlackBerry/i.test(navigator.userAgent);var isiPad=/iPad/i.test(navigator.userAgent);$(window).resize(function(){responsiveResize();responsiveResize2();});$(document).ready(function(){controller=new ScrollMagic();highdpiInit();responsiveResize();responsiveResize2();homefeatured();if($('#layered_block_left').length<1){$('.block-filter_btn  .filter_btn').hide();};$("body").on('click','.filter_btn',function(){if($('.filter_btn').hasClass('active')){$('.filter_btn').removeClass('active');$('body #layered_block_left').removeClass('visible');}else{$('.filter_btn').addClass('active');$('.vicevle_box').addClass('visible');$('body #layered_block_left').addClass('visible');}});$("body").on('click','.vicevle_box.visible',function(){$('.filter_btn').removeClass('active');$(this).removeClass('visible');$('body #layered_block_left').removeClass('visible');});$('#layered_block_left #layered_form ul li input.on').parent().addClass('color-on');$('#product_comments_block_extra, #usefull_link_block').appendTo('.content_prices');$('.socialsharing_product').appendTo('.box-btn-cosial');$('.wishlist-prodict, #usefull_link_block').prependTo('#image-block');$("#product-nav ul li:first-child a").addClass('active');$("#product-nav ul li a").click(function(e){e.preventDefault();$("#product-nav ul li a").removeClass('active');$(this).addClass('active');})
$(".tmmp_row_6 > li").each(function(index){$(this).attr("id","item"+index);});$("#homepage-blog  li").each(function(index){$(this).attr("id","item"+index);});$('#layered_block_left #layered_form .layered_filter .layered_filter_ul.color-group li > input ,#attributes .attribute_list #color_to_pick_list li a , ul.product_list .color-list-container ul li > a, ul.product_list .color-list-container ul li > input').each(function(){if(rgb2hex($(this).css('background-color'))=='#ffffff'){$(this).addClass('white-color');}});$("#layer_cart").appendTo(".nav nav");$(".layer_cart_overlay").appendTo(".nav nav");$(document).on('click',function(e){var container=$('#tmsearch');var search_query_wrapper=$('#tmsearch .tm_search_query_wrapper');var visible_btn=$('#tmsearch .visible_btn');if(container.has(e.target).length===0){if(search_query_wrapper.hasClass('search_animate_in')){search_query_wrapper.addClass('search_animate_out').removeClass('search_animate_in');visible_btn.removeClass('hiden').show();visible_btn.removeClass('in_active');setTimeout(function(){search_query_wrapper.removeClass('search_animate_out');},1000);}}});if(navigator.userAgent.match(/Android/i)){var viewport=document.querySelector('meta[name="viewport"]');viewport.setAttribute('content','initial-scale=1.0,maximum-scale=1.0,user-scalable=0,width=device-width,height=device-height');window.scrollTo(0,1);}
blockHover();if(typeof quickView!=='undefined'&&quickView){quick_view();}
dropDownFade();showHide();sitemapAccordion();counter();testimonialsSlider();visible_btn_hover();$('#tmsearch .visible_btn').on('click',function(){search_btn($(this));});if(typeof page_name!='undefined'&&!in_array(page_name,['index','product'])){bindGrid();$(document).on('change','.selectProductSort',function(e){if(typeof request!='undefined'&&request){var requestSortProducts=request;}
var splitData=$(this).val().split(':');var url='';if(typeof requestSortProducts!='undefined'&&requestSortProducts){url+=requestSortProducts;if(typeof splitData[0]!=='undefined'&&splitData[0]){url+=(requestSortProducts.indexOf('?')<0?'?':'&')+'orderby='+ splitData[0]+(splitData[1]?'&orderway='+ splitData[1]:'');if(typeof splitData[1]!=='undefined'&&splitData[1]){url+='&orderway='+ splitData[1];}}
document.location.href=url;}});$(document).on('change','select[name="n"]',function(){$(this.form).submit();});$(document).on('change','select[name="currency_payment"]',function(){setCurrency($(this).val());});}
$(document).on('change','select[name="manufacturer_list"], select[name="supplier_list"]',function(){if(this.value!=''){location.href=this.value;}});$(document).on('click','.back',function(e){e.preventDefault();history.back();});jQuery.curCSS=jQuery.css;if(!!$.prototype.cluetip){$('a.cluetip').cluetip({local:true,cursor:'pointer',dropShadow:false,dropShadowSteps:0,showTitle:false,tracking:true,sticky:false,mouseOutClose:true,fx:{open:'fadeIn',openSpeed:'fast'}}).css('opacity',0.8);}
if(typeof(FancyboxI18nClose)!=='undefined'&&typeof(FancyboxI18nNext)!=='undefined'&&typeof(FancyboxI18nPrev)!=='undefined'&&!!$.prototype.fancybox){$.extend($.fancybox.defaults.tpl,{closeBtn:'<a title="'+ FancyboxI18nClose+'" class="fancybox-item fancybox-close" href="javascript:;"></a>',next:'<a title="'+ FancyboxI18nNext+'" class="fancybox-nav fancybox-next" href="javascript:;"><span></span></a>',prev:'<a title="'+ FancyboxI18nPrev+'" class="fancybox-nav fancybox-prev" href="javascript:;"><span></span></a>'});}
$('.alert.alert-danger').on('click',this,function(e){if(e.offsetX>=16&&e.offsetX<=39&&e.offsetY>=16&&e.offsetY<=34){$(this).fadeOut();}});});function highdpiInit(){if(typeof highDPI==='undefined'){return;}
if(highDPI&&$('.replace-2x').css('font-size')=='1px'){var els=$('img.replace-2x').get();for(var i=0;i<els.length;i++){src=els[i].src;extension=src.substr((src.lastIndexOf('.')+1));src=src.replace('.'+ extension,'2x.'+ extension);var img=new Image();img.src=src;img.height!=0?els[i].src=src:els[i].src=els[i].src;}}}
function scrollCompensate(){var inner=document.createElement('p');inner.style.width='100%';inner.style.height='200px';var outer=document.createElement('div');outer.style.position='absolute';outer.style.top='0px';outer.style.left='0px';outer.style.visibility='hidden';outer.style.width='200px';outer.style.height='150px';outer.style.overflow='hidden';outer.appendChild(inner);document.body.appendChild(outer);var w1=inner.offsetWidth;outer.style.overflow='scroll';var w2=inner.offsetWidth;if(w1==w2){w2=outer.clientWidth;}
document.body.removeChild(outer);return(w1- w2);}
function responsiveResize(){var compensante=scrollCompensate();if(($(window).width()+scrollCompensate())<=767&&responsiveflag==false){accordion('enable');accordionFooter('enable');accordionFooterExtra('enable');tabletResize('enable');responsiveflag=true;}else if(($(window).width()+scrollCompensate())>=768){accordion('disable');accordionFooter('disable');accordionFooterExtra('disable');tabletResize('disable');responsiveflag=false;if(typeof bindUniform!=='undefined'){bindUniform();}}}
function responsiveResize2(){var compensante=scrollCompensate();if(($(window).width()+scrollCompensate())<=479&&responsiveflag2==false){mobileResize('enable');responsiveflag2=true;}else if(($(window).width()+scrollCompensate())>480&&responsiveflag2==true){mobileResize('disable');responsiveflag2=false;}}
function blockHover(status){$(document).off('mouseenter').on('mouseenter','.product_list.grid li.ajax_block_product .product-container',function(e){if('ontouchstart'in document.documentElement){return;}
if($('body').find('.container').width()==1170){$(this).parent().addClass('hovered');}});$(document).off('mouseleave').on('mouseleave','.product_list.grid li.ajax_block_product .product-container',function(e){if($('body').find('.container').width()==1170){$(this).parent().removeClass('hovered');}});}
function quick_view(){$(document).on('click','.quick-view:visible, .quick-view-mobile:visible',function(e){e.preventDefault();var url=$(this).attr('data-href');if(!url&&url=='undefined'){var url=this.rel;}
var anchor='';if(url.indexOf('#')!=-1){anchor=url.substring(url.indexOf('#'),url.length);url=url.substring(0,url.indexOf('#'));}
if(url.indexOf('?')!=-1){url+='&';}else{url+='?';}
if(!!$.prototype.fancybox){$.fancybox({'transitionIn':'fade','transitionOut':'elastic','padding':0,'width':1356,'height':700,'type':'iframe','href':url+'content_only=1'+ anchor,tpl:{closeBtn:'<a title="Close" class="fancybox-close product-popup-close" href="javascript:;"></a>'}});}});}
function bindGrid(){var storage=false;if(typeof(getStorageAvailable)!=='undefined'){storage=getStorageAvailable();}
if(!storage){return;}
var view=$.totalStorage('display');if(!view&&(typeof displayList!='undefined')&&displayList){view='list';}
if(view&&view!='grid'){display(view);}else{$('.display').find('li#grid').addClass('selected');}
$(document).on('click','#grid, #list',function(e){e.preventDefault();if(!$(this).hasClass('selected')){display($(this).attr('id'));}});}
if(nbItemsPerLine!='undefined'&&nbItemsPerLineTablet!='undefined'&&nbItemsPerLineMobile!='undefined'){var nbItemsPerLine=nbItemsPerLine;var nbItemsPerLineTablet=nbItemsPerLineTablet
var nbItemsPerLineMobile=nbItemsPerLineMobile}else{var nbItemsPerLine='';var nbItemsPerLineTablet='';var nbItemsPerLineMobile='';}
function display(view){if(view=='list'){$('ul.product_list').removeClass('grid').addClass('list row');$('.product_list > li:visible').removeAttr('class').addClass('ajax_block_product col-xs-12');$('.product_list > li:visible').each(function(index,element){var html='';html='<div class="product-container"><div class="row">';html+='<div class="left-block col-xs-6">';html+=$(element).find('.product-image-container').wrap('<div>').parent().html();html+=$(element).find('.functional-buttons').wrap('<div>').parent().html();html+=$(element).find('.lnk_view.btn.btn-sm.btn-default').wrap('<div>').parent().html();html+='</div>';html+='<div class="center-block col-xs-6 ">';html+='<div class="product-flags">'+ $(element).find('.product-flags').html()+'</div>';var hookReviews=$(element).find('.hook-reviews');if(hookReviews.length){html+=hookReviews.clone().wrap('<div>').parent().html();}
html+='<h5 itemprop="name">'+ $(element).find('h5').html()+'</h5>';html+='<p class="product-desc">'+ $(element).find('.product-desc').html()+'</p>';html+='<div class="right-block "><div class="right-block-content">';var price=$(element).find('.content_price').html();if(price!=null){html+='<div class="content_price">'+ price+'</div>';}
var colorList=$(element).find('.color-list-container').html();if(colorList!=null){html+='<div class="color-list-container">'+ colorList+'</div>';}
var availability=$(element).find('.availability').html();if(availability!=null){html+='<span class="availability">'+ availability+'</span>';}
html+='<div class="button-container clearfix">'+ $(element).find('.button-container').html()+'</div>';html+='</div>';html+='</div>';html+='</div></div>';$(element).html(html);});$('.display').find('li#list').addClass('selected');$('.display').find('li#grid').removeAttr('class');listTabsAnimate('ul.product_list>li');$.totalStorage('display','list');if($('.product_list li div.wishlist').length){WishlistButton();}}else{$('ul.product_list').removeClass('list').addClass('grid row');var totModulo=($('.product_list > li').length)%nbItemsPerLine;totModulo==0?totModulo=nbItemsPerLine:totModulo=totModulo;var totModuloLine=($('.product_list > li').length)- totModulo;var totModuloTab=($('.product_list > li').length)%nbItemsPerLineTablet;totModuloTab==0?totModuloTab=nbItemsPerLineTablet:totModuloTab=totModuloTab;var totModuloTabLine=($('.product_list > li').length)- totModuloTab;var totModuloMob=($('.product_list > li').length)%nbItemsPerLineMobile;totModuloMob==0?totModuloMob=nbItemsPerLineMobile:totModuloMob=totModuloMob;var totModuloMobLine=($('.product_list > li').length)- totModuloMob;$('.product_list > li:visible').each(function(index,element){$(element).removeAttr('class').addClass('ajax_block_product col-xs-'+ 12/nbItemsPerLineMobile+' col-sm-'+ 12/nbItemsPerLineTablet+' col-md-'+ 12/nbItemsPerLine);(index+ 1)%nbItemsPerLine==0?$(element).addClass('last-in-line'):false;(index+ 1)%nbItemsPerLine==1?$(element).addClass('first-in-line'):false;(index+ 1)>totModuloLine?$(element).addClass('last-line'):false;(index+ 1)%nbItemsPerLineTablet==0?$(element).addClass('last-item-of-tablet-line'):false;(index+ 1)%nbItemsPerLineTablet==1?$(element).addClass('first-item-of-tablet-line'):false;(index+ 1)>totModuloTabLine?$(element).addClass('last-tablet-line'):false;(index+ 1)%nbItemsPerLineMobile==0?$(element).addClass('last-item-of-mobile-line'):false;(index+ 1)%nbItemsPerLineMobile==1?$(element).addClass('first-item-of-mobile-line'):false;(index+ 1)>totModuloMobLine?$(element).addClass('last-mobile-line'):false;var html='';html+='<div class="product-container">';html+='<div class="left-block">'+ $(element).find('.left-block').html()+'</div>';html+='<div class="right-block">';var hookReviews=$(element).find('.hook-reviews');if(hookReviews.length){html+=hookReviews.clone().wrap('<div>').parent().html();}
html+='<div class="product-flags">'+ $(element).find('.product-flags').html()+'</div>';var availability=$(element).find('.availability').html();if(availability!=null){html+='<span class="availability">'+ availability+'</span>';}
html+='<h5 itemprop="name">'+ $(element).find('h5').html()+'</h5>';html+='<p itemprop="description" class="product-desc">'+ $(element).find('.product-desc').html()+'</p>';var price=$(element).find('.content_price').html();if(price!=null){html+='<div class="content_price">'+ price+'</div>';}
var colorList=$(element).find('.color-list-container').html();if(colorList!=null){html+='<div class="color-list-container">'+ colorList+'</div>';}
html+='<div class="button-container clearfix">'+ $(element).find('.button-container').html()+'</div>';html+='</div>';html+='</div>';$(element).html(html);});$('.display').find('li#grid').addClass('selected');$('.display').find('li#list').removeAttr('class');listTabsAnimate('ul.product_list>li');$.totalStorage('display','grid');if($('.product_list li div.wishlist').length){WishlistButton();}}}
function dropDownFade(){elementClick1='#header .current_toogle';elementSlide1='ul.toogle_content_box';activeClass1='active';inactiveClass1='inactive';$(elementClick1).on('click',function(e){e.stopPropagation();var subUl=$(this).next(elementSlide1);if(subUl.is(':hidden')){subUl.fadeIn(200,"swing");$(this).addClass(activeClass1);$(this).removeClass(inactiveClass1);}else{subUl.fadeOut(200,"swing");$(this).removeClass(activeClass1);$(this).addClass(inactiveClass1);}
$(elementClick1).not(this).next(elementSlide1).fadeOut(200,"swing");$(elementClick1).not(this).removeClass(activeClass1);$(elementClick1).not(this).addClass(inactiveClass1);e.preventDefault();});$(elementSlide1).on('click',function(e){e.stopPropagation();});$(document).on('click',function(e){e.stopPropagation();if(e.which!=3){var elementHide1=$(elementClick1).next(elementSlide1);$(elementHide1).fadeOut(200,"swing");$(elementClick1).removeClass(activeClass1);$(elementClick1).addClass(inactiveClass1);}});$('.icon-close').on('click',function(e){e.stopPropagation();var elementHide1=$(elementClick1).next(elementSlide1);$(elementHide1).fadeOut(200,"swing");$(elementClick1).removeClass(activeClass1);$(elementClick1).addClass(inactiveClass1);});}
function showHide(){elementClick2='.btn-setting';elementSlide2='.toogle_box';activeClass2='active';$(elementClick2).on('click',function(e){e.stopPropagation();var subUl=$(this).next(elementSlide2);if(subUl.is(':hidden'))
{subUl.fadeIn(200);$(this).addClass(activeClass2);}
else{subUl.fadeOut(200);$(this).removeClass(activeClass2);}
$(elementClick2).not(this).next(elementSlide2).hide();$(elementClick2).not(this).removeClass(activeClass2);e.preventDefault();});$(elementSlide2).on('click',function(e){e.stopPropagation();});$(document).on('click',function(e){e.stopPropagation();var elementHide2=$(elementClick2).next(elementSlide2);$(elementHide2).fadeOut(200);$(elementClick2).removeClass('active');});}
function accordionFooter(status){if(status=='enable'){$('#footer .footer-block h4').on('click',function(e){$(this).toggleClass('active').parent().parent().find('.toggle-footer').stop().slideToggle('medium');e.preventDefault();});$('#footer').addClass('accordion').find('.toggle-footer').slideUp('fast');}else{$('.footer-block h4').removeClass('active').off().parent().parent().find('.toggle-footer').removeAttr('style').slideDown('fast');$('#footer').removeClass('accordion');}}
function accordionFooterExtra(status){if(status=='enable'){$('#footer #newsletter_block_left h4').on('click',function(e){$(this).toggleClass('active').parent().parent().parent().find('.toggle-footer').stop().slideToggle('medium');e.preventDefault();});$('#footer').addClass('accordion').find('.toggle-footer').slideUp('fast');}else{$('#newsletter_block_left h4').removeClass('active').off().parent().parent().parent().find('.toggle-footer').removeAttr('style').slideDown('fast');$('#footer').removeClass('accordion');}}
function accordion(status){if(status=='enable'){$('#product .product-information .tab-content > h3, #right_column .block:not(#layered_block_left) .title_block, #left_column .block:not(#layered_block_left) .title_block, #left_column #newsletter_block_left h4').on('click',function(){$(this).toggleClass('active').parent().find('.block_content').stop().slideToggle('medium');$(this).next('.tab-pane').stop().slideToggle('medium');});$('#right_column, #left_column').addClass('accordion').find('.block:not(#layered_block_left) .block_content').slideUp('fast');$('#product .product-information .tab-content > h3:first').addClass('active');if(typeof(ajaxCart)!=='undefined'){ajaxCart.collapse();}}else{$('#product .product-information .tab-content > h3, #right_column .block:not(#layered_block_left) .title_block, #left_column .block:not(#layered_block_left) .title_block, #left_column #newsletter_block_left h4').removeClass('active').off().parent().find('.block_content, .tab-pane').removeAttr('style').not('.tab-pane').slideDown('fast');$('#left_column, #right_column').removeClass('accordion');$('#product .product-information .tab-content > h3:first').addClass('active');}}
function bindUniform(){if(!!$.prototype.uniform){$('select.form-control').not('.not_uniform').uniform();}}
function listBlocksAnimate(block,element,row,offset,difEffect){if(!isMobile&&jQuery(block).length){var i=0;var j=row;var k=1;var effect=-1;$(element).each(function(){i++;if(i>j){j+=row;k=i;effect=effect*(-1);}
effect==-1&&difEffect==true?ef=TweenMax.from(element+':nth-child('+i+')',0.5,{left:-1*200-i*300+'px',alpha:0,ease:Power1.easeOut}):ef=TweenMax.from(element+':nth-child('+i+')',0.5,{right:-1*200-i*300+'px',alpha:0,ease:Power1.easeOut});var scene_new=new ScrollScene({triggerElement:element+':nth-child('+k+')',offset:offset,}).setTween(ef).addTo(controller).reverse(false);});}}
function listTabsAnimate(element){if(!isMobile&&jQuery(element).length&&!$('#old_center_column').length){TweenMax.staggerFromTo(element,0.3,{alpha:0,ease:Power1.easeOut},{alpha:1,ease:Power1.easeOut},0.1);}}
$(window).load(function(){listTabsAnimate('ul.product_list:not(".tab-pane")>li');$(".top_menu > ul > li > a").each(function(){if($(this).hasClass("sf-with-ul")){$(this).append('<span class="item-angle"></span>');}})
$("#tmhtmlcontent_topColumn").mCustomScrollbar({axis:"x",theme:"rounded-dots",contentTouchScroll:false,advanced:{autoExpandHorizontalScroll:true},callbacks:{onOverflowX:function(){var opt=$(this).data("mCS").opt;if(opt.mouseWheel.axis!=="x")opt.mouseWheel.axis="x";},}});$("#header-login #header-login-content >li").each(function(){if($(this).hasClass("login")){$(this).parent().parent().addClass('active-login')}})
$('.top_menu').on('click',function(event){if($(event.target).is('.menu-close')){$('.top_menu').find('.menu-title').removeClass('active');event.preventDefault();}});});function sitemapAccordion(){$('#sitemap #center_column ul.tree > li > ul').addClass('accordion_content').parent().find('> a').wrap('<p class="page-subheading accordion_current"></p>');$('#center_column .accordion_current').on('click',function(){$(this).toggleClass('active').parent().find('.accordion_content').stop().slideToggle('medium');});$('#center_column').addClass('accordionBox').find('.accordion_content').slideUp('fast');if(typeof(ajaxCart)!=='undefined'){ajaxCart.collapse();}}
function counter(){$('.count').each(function(){$(this).prop('Counter',0).animate({Counter:$(this).text()},{duration:4000,easing:'swing',step:function(now){$(this).text(Math.ceil(now));}});});}
function testimonialsSlider(){var testimonials_slider=$('#testimonials');testimonials_slider.bxSlider({responsive:true,useCSS:false,minSlides:1,maxSlides:1,slideWidth:1200,slideMargin:0,moveSlides:1,pager:false,autoHover:false,speed:500,pause:3000,controls:true,autoControls:true,startText:'',stopText:'',prevText:'',nextText:''});}
function tabletResize(status){if(status=='enable'){$('.header_links').appendTo('.block-setting');$('.block-setting').addClass('toogle_box');$('#newsletter_block_left').addClass('footer-block');$('#newsletter_block_left .block_content').addClass('toggle-footer');$('.extra-social-block').prependTo('.footer-extra-col');}else{$('.header_links').appendTo('nav');$('.block-setting').removeClass('toogle_box');$('#newsletter_block_left').removeClass('footer-block');$('#newsletter_block_left .block_content').removeClass('toggle-footer');$('.extra-social-block').appendTo('.footer-extra-col');}}
function mobileResize(status){if(status=='enable'){$('#languages-block-top, #currencies-block-top , #header-login').appendTo('.block-setting');}else{$('#languages-block-top, #currencies-block-top , #header-login').appendTo('.nav nav');}}
function search_btn(element){$('#tmsearch .tm_search_query_wrapper').addClass('search_animate_in');$('#tmsearch .button-search').addClass('in_active');$(element).addClass('hiden').hide(1000);}
function visible_btn_hover(){var btn=$('#tmsearchbox .visible_btn');var btn_search=$('#tmsearchbox .button-search');if(btn.length>0){btn.hover(function(){btn_search.addClass('active_btn');},function(){btn_search.removeClass('active_btn');});}}
function rgb2hex(rgb){if(rgb.match(/^rgba?\((\d+),\s*(\d+),\s*(\d+)(?:,\s*(\d+))?\)$/)){rgb=rgb.match(/^rgba?\((\d+),\s*(\d+),\s*(\d+)(?:,\s*(\d+))?\)$/);function hex(x){return("0"+ parseInt(x).toString(16)).slice(-2);}
return"#"+ hex(rgb[1])+ hex(rgb[2])+ hex(rgb[3]);}}
$(window).on("load",function(){$("#page_preloader").addClass("fade").fadeOut("1000");});function homefeatured(){if($('.home-preset1 #homefeatured li').length){$(".home-preset1 #homefeatured").slick({infinite:true,dots:true,adaptiveHeight:true,prevArrow:false,nextArrow:false,slidesToShow:3,slidesToScroll:1,responsive:[{breakpoint:1170,settings:{slidesToShow:3,slidesToScroll:1}},{breakpoint:991,settings:{slidesToShow:2,slidesToScroll:2}},{breakpoint:768,settings:{slidesToShow:2,slidesToScroll:2,prevArrow:false,nextArrow:false}},{breakpoint:480,settings:{slidesToShow:1,slidesToScroll:1,prevArrow:'<button type="button" data-role="none" class="slick-prev" aria-label="Previous" tabindex="0" role="button"></button>',nextArrow:'<button type="button" data-role="none" class="slick-next" aria-label="Next" tabindex="0" role="button"></button>',dots:false}}]});}}